#DB
spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:3306/BDD_TRANSACTIONAL
spring.datasource.username=root
spring.datasource.password=root

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#LOG
logging.file.name=logs/transactional-microservice.log
logging.level.root=INFO
logging.level.com.project=DEBUG
logging.level.org.springframework=INFO

server.port=8081
server.error.include-message=always
server.transactional-domain=${CLIENT_HOST:localhost}