input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  json {
    source => "message"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microservices-logs-%{+YYYY.MM.dd}"
    ilm_enabled => false
  }
  stdout { codec => rubydebug }
}